### PR TITLE
trying to replicate bug with exclude paths

### PR DESCRIPTION
**Pull request by noahd1**
Report is that issues are still reported even if excluded

### CODE REVIEW

**Comment by wfleming** [comment]
I can confirm this happened for me locally at some point, but I'm not sure I do anymore. It may have been fixed, if the user is running an older CC or engines?

**Comment by noahd1** [comment]
The bug being reported: exclude paths not being honored in a PR that changes exclude paths in the .codeclimate.yml
Platform: CC:E
Version of engines: fairly recent? They installed a week before x-mas.

@wfleming Do you have any more details on the bug that you think was fixed?

**Comment by wfleming** [comment]
I just confirmed that the bug is _not_ fixed in my particular case.

Basically, I added `.bundle/**/*` to our app's .codeclimate.yml a long time ago (my personal habit is to bundle to a local `.bundle` directory for all projects). When I run `codeclimate analyze` locally, issues are reported on files in bundled gems (by a variety of engines, so I don't believe it's a single-engine issue).

**Comment by noahd1** [comment]
Not sure if it's related but at least you have a reproducible case which I
do not. Seems worth tracking down.

**Pull request closed without merging**
